### ISSUE TITLE
Mejorar documentación

### ISSUE THREAD

**Issue by lmorillas** [mariaestmag/libreria-musical#1]
## README

* Pon la dirección de tu repositorio, no una genérica para clonar.
* Còmo se pone en marcha la web?
* Añade una descripción de la web y sus funcionalidades

**Comment by mariaestmag** [comment]
Mejoré un poco el README y añadí a .gitignore el .DS_Store para que en sucesivas subidas no lo coja. Previamente me deshice del que había en el repositorio.
