### ISSUE TITLE
Índice

### ISSUE THREAD

**Issue by lmorillas** [mariaestmag/libreria-musical#4]
Seguro que quieres mostrar todos los álbumes en el índice?

Gestión de las imágenes en los card: 
* https://github.com/mariaestmag/libreria-musical/blob/5f3023bee26200c25cfb7608048d9421e55d4f08/musica/templates/index.html#L11
* https://github.com/mariaestmag/libreria-musical/blob/5f3023bee26200c25cfb7608048d9421e55d4f08/musica/templates/index.html#L12

**Comment by mariaestmag** [comment]
> Seguro que quieres mostrar todos los álbumes en el índice?

No se me ocurría qué incluir pero estoy abierta a sugerencias. Supongo que a modo de recordatorio sobre lo último añadido en la web era un concepto que tenía sentido en mi cabeza...

> Gestión de las imágenes en los card:

Añadí una pequeña mejora para que, en caso de que no se haya subido foto, muestre un icono not-found por defecto:
[index.html]

```
{% if album.cover %}
 <img src="{{ album.cover.url }}" class="card-img-top" alt="preview-album">
 {% else %}
 <p>No hay foto</p>
  {% endif %}
```
