### ISSUE TITLE
Añadir búsquedas al Admin

### ISSUE THREAD

**Issue by lmorillas** [mariaestmag/libreria-musical#5]
* Añade búsquedas al admin
* ¿Filtrar canciones por el genero?
* ¿Filtrar artistas por genero?

**Comment by mariaestmag** [comment]
> * Añade búsquedas al admin

> * ¿Filtrar canciones por el genero?

> * ¿Filtrar artistas por genero?  

A través de search_fields en admin.py lo consigo hacer pero no puedo mostrar una columna en el panel de administración por integridad referencial: primero tengo que crear la entidad Artista y luego la entidad Album...no puedo tener un atributo en artista que por manytomany referencie a album.
